# Generated by Django 6.1.1 on 2026-09-20 01:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_bio_and_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=accounts.models.profile_upload_to),
        ),
    ]
