[build]
  command = "npm ci --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "https://web-production-a1efa.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media/*"
  to = "https://web-production-a1efa.up.railway.app/media/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
