# Generated by Django 6.1.1 on 2026-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meeting_started',
            field=models.BooleanField(default=False),
        ),
    ]
