# Generated by Django 6.1.1 on 2026-09-20 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_meeting_started'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icebreaker_question', models.TextField(blank=True)),
                ('user_one_answer', models.TextField(blank=True)),
                ('user_two_answer', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rounds', to='rooms.room')),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rounds_as_user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rounds_as_user_two', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
