# Generated by Django 6.1.1 on 2026-09-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_allow_null_score_reasons'),
        ('rooms', '0003_exchangeround'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeround',
            name='user_one_gives_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.card'),
        ),
        migrations.AddField(
            model_name='exchangeround',
            name='user_one_wants_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.card'),
        ),
        migrations.AddField(
            model_name='exchangeround',
            name='user_two_gives_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.card'),
        ),
        migrations.AddField(
            model_name='exchangeround',
            name='user_two_wants_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cards.card'),
        ),
    ]
