# Generated by Django 6.1.1 on 2026-09-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards/')),
                ('story', models.TextField(blank=True)),
                ('photo_quality', models.IntegerField()),
                ('location_significance', models.IntegerField()),
                ('occasion', models.IntegerField()),
                ('uniqueness', models.IntegerField()),
                ('memory_story', models.IntegerField()),
                ('overall_score', models.IntegerField()),
                ('rarity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
