# Generated by Django 6.1.1 on 2026-09-20 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_openings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackPull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_pulls', to='cards.card')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifted_pack_cards', to=settings.AUTH_USER_MODEL)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulls', to='cards.packopening')),
            ],
        ),
    ]
