# Generated by Django 6.1.1 on 2026-09-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_packopening_packpull'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packpull',
            options={'ordering': ['id']},
        ),
    ]
