# Generated by Django 6.1.1 on 2026-09-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_card_image_content_type_card_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='location_significance_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='memory_story_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='occasion_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='photo_quality_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='uniqueness_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
